### ISSUE TITLE
Can't scroll trough project list 

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#1]
_From @GaruGaru on June 30, 2017 16:13_

Can't scroll the project list when adding a cluster using the 'GKE' options

_Copied from original issue: skippbox/cabin-issues#26_

**Comment by sebgoa** [comment]
What platform and what version are you on ? iOS/android

**Comment by sebgoa** [comment]
_From @GaruGaru on July 2, 2017 9:10_

I'm on android the scroll isn't working both in landscape and vertical mode

![1](https://user-images.githubusercontent.com/6578583/27768606-d0647780-5f17-11e7-8953-a981b1076831.jpg)


Tried in:
- Samsung galaxy s6
- Zuk z2

**Comment by MartinodF** [comment]
+1, same issue on Android 8.0.0 on a Pixel XL. I may be wrong, but I seem to remember this issue has been there since the first time I used Cabin.

**Comment by kemcake** [comment]
Fixed, this was an issue with @expo/react-native-action-sheet. A PR is open on their repo, using a fork for now on Cabin
