### ISSUE TITLE
Can't display objects with same name in different namespaces

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#10]
_From @IanLewis on November 23, 2016 15:23_

Objects like pods/deployments/secrets etc. can have duplicate names in different namespaces but cabin only shows one of them when viewing with the "all namespaces" filter.

_Copied from original issue: skippbox/cabin-issues#17_

**Comment by sebgoa** [comment]
ah ah, good catch. will fix.

**Comment by kemcake** [comment]
@sebgoa this issue has been fixed, we're using uid instead of name to as react's key attribute now
