### ISSUE TITLE
Dynamic Fonts

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#13]
_From @GEverding on August 22, 2016 22:37_

Hi, love the app. I use dynamic fonts on iOS (Accessibility Option) and the headers and labels aren't scaling appropriately. 
![slack for ios upload png](https://cloud.githubusercontent.com/assets/1377740/17874078/6a6bdb34-6897-11e6-86f9-2a3745a87d18.jpeg)

_Copied from original issue: skippbox/cabin-issues#10_

**Comment by sebgoa** [comment]
Hi, thanks for filing this issue. Indeed, we did not test this. Hopefullt we will be able to fix it quickly.

Thanks again for reporting it,

**Comment by sebgoa** [comment]
_From @GEverding on November 22, 2016 2:8_

Hey, is this issues still being worked on?

**Comment by sebgoa** [comment]
It should be much better in the latest version, did you update ?

**Comment by sebgoa** [comment]
_From @GEverding on November 27, 2016 2:11_

It is better with the latest update. It's great to see. 

--
Garrett




On Tue, Nov 22, 2016 at 3:01 AM -0500, "sebgoa" <notifications@github.com> wrote:












It should be much better in the latest version, did you update ?

**Comment by sebgoa** [comment]
ok we will try to keep improving this, but can we close this for now ?

**Comment by kemcake** [comment]
@sebgoa this works pretty well, *obviously extra-extra-large font size might looks weird, but shouldn't break anyway*
