### ISSUE TITLE
More compact list display?

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#14]
_From @mboersma on August 10, 2016 20:0_

The default list view fits only 3.5 items vertically, at least on my iPhone 6. I have exactly 8 clusters (currently) that I'd like to keep an eye on, so a more compact view that only shows only name and running status could be a more useful default.

_Copied from original issue: skippbox/cabin-issues#8_

**Comment by kemcake** [comment]
Cabin already handle this by reducing the size of the cluster when you have more than 5 clusters:

![simulator screen shot 10 aug 2017 09 48 48](https://user-images.githubusercontent.com/4311124/29181805-54330358-7db1-11e7-83d6-2d2cd7487262.png)


Maybe we can reduce it more? cc @sebgoa @mboersma
