### ISSUE TITLE
Unable to add cluster running in Google Container Engine 

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#4]
_From @Jacobh2 on March 4, 2017 7:7_

I've tried to reinstall the app, cleared the cache and data and I still run into this problem. 

When I choose to add a GKE cluster, it asks me to select correct Google account, and then it shows me the cluster and that it is up and running. A green notification shows that it has added the cluster successfully, but when I return to the home screen it shows my cluster as "down" when it most certainly is not. 

Selecting the cluster takes me to the page of pods, ns, svc etc but nothing is there. 

What am I missing? 

_Copied from original issue: skippbox/cabin-issues#23_

**Comment by sebgoa** [comment]
Thanks for reporting the issue.

Are you on iOS or android ?

can you confirm that you can use `kubectl` to access the cluster from a machine in a different network ?

cc/ @kemcake

**Comment by sebgoa** [comment]
_From @Jacobh2 on March 6, 2017 14:34_

Hi!

I'm using Android. When I started to test the app I was on version 6.?, but now I'm using 7.0.

Yes, I can access the cluster using `kubectl` on any network.

**Comment by sebgoa** [comment]
ok, we will test for 7.0 and figure it out. it could be the version change.

we will try to fix this asap.

**Comment by DylanGraham** [comment]
Hi I have the same problem.
App version 0.3.1
OS Android 8
Cluster version 1.7.4.

Thanks, love the app, it was working on a previous cluster. I'll test some more versions.

**Comment by DylanGraham** [comment]
2 more test clusters that are showing as **down**

    NAME      ZONE        MASTER_VERSION  MASTER_IP       MACHINE_TYPE   NODE_VERSION  NUM_NODES  STATUS
    testing   us-west1-c  1.7.4           XX.XXX.XXX.XXX  n1-standard-1  1.7.4         1          RUNNING
    testing2  us-west1-c  1.6.9           XX.XXX.XX.XXX   n1-standard-1  1.6.9         1          RUNNING`

**Comment by kemcake** [comment]
Ok I think this is an issue with how Android http request handle certificates, will investigate a fix 💪

**Comment by fiws** [comment]
Same problem. It worked sometime. I think it stopped working after I registered a Gmail address for my account.

**Comment by Jacobh2** [comment]
Still have the same issue using version 0.3.1 of the app.

Phone model: SM-G950F
Android version: 7.0
Node version: 1.5.6

Also, after adding the cluster via the "Add cluster from Google GKE", and the pressing back to go to start activity the add adds a border around the entire app: https://photos.app.goo.gl/CcP2VMp8PNY1SX9e2

**Comment by vtuson** [comment]
I have the same problem, It *used* to work fine but suddenly stop working so I am not sure @kemcake comment about how android http request is handle the issue here, since it work fine for weeks.

I have set up the dev environment of Cabin to try to debug it but I can set up a project id to test GKE auth :(

**Comment by kemcake** [comment]
So, update on this, I think I finally found the issue, it comes from react native itself with a breaking commit (https://github.com/facebook/react-native/commit/0a71f48b1349ed09bcb6e76ba9ff8eb388518b15). I'm trying to find a clean solution to override this change (maybe a fork, or using `patch-package`)

**Comment by vtuson** [comment]
@kemcake fwiw, my cluster api from google seems to be using a selfsigned cert. Doesnt seem to be a good way in android to make react-native ignore it. Not sure if it related.

**Comment by kemcake** [comment]
In cabin on android we override how https request are handled, by adding a manual logic to include authentication certificates (if needed) and allowing every self-signed certificates challenge. 
(see https://github.com/bitnami/cabin/blob/99c7f0cc81f501aabd649afcb37fd84e95c753d2/android/app/src/main/java/com/skippbox/cabin/CertificateModule.java)

**Comment by kemcake** [comment]
So this should be fixed with https connection issue on android #72 . Released in 0.4.X
