### ISSUE TITLE
Please add more screenshots!

### ISSUE THREAD

**Issue by dankohn** [bitnami/cabin#54]
Your Readme is your main opportunity to sell people on the project. Please include another 3 or 4 screenshots to show what it can do.

**Comment by kemcake** [comment]
cc @sebgoa, replacing the actual pixelated screenshot with a gif or multiple screenshots might be a good idea.

**Comment by sebgoa** [comment]
the first pic is actually a screencast. if you click on it plays a movie...

but yes, we will improve this (just back from break)

**Comment by dankohn** [comment]
It's not clear from the text that it links to a video. But screenshots are
even better.

--
Dan Kohn <mailto:dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by sebgoa** [comment]
@dankohn can you check now, let me know what you think, thanks

**Comment by dankohn** [comment]
Looks fantastic. Huge improvement, thanks.
