### ISSUE TITLE
Can't fetch store error

### ISSUE THREAD

**Issue by migmartri** [bitnami/cabin#56]
Hi,

The app returns a 404 error while retrieving the list of charts, maybe related to a wrong charts repository?

![screenshot_20170802-175536 1](https://user-images.githubusercontent.com/24523/28901744-3eeab26e-77af-11e7-9108-5185dbfe83a2.png)

![screenshot_20170802-175243 1](https://user-images.githubusercontent.com/24523/28901750-4623a7f2-77af-11e7-9b3a-3a25fd5788fe.png)

Also, the adding new chart repository link/button at the bottom of the official one does not seem functional not being visible.

**Comment by kemcake** [comment]
Cannot reproduce 404 🤔 (Adding a new chart store is fixed, see #57)

![screenshot 2017-08-09 16 20 55](https://user-images.githubusercontent.com/4311124/29147904-ea3b7f58-7d1e-11e7-8ff5-ca06f8140ba7.png)

**Comment by sebgoa** [comment]
@kemcake this is an intermittent issue. I also face it. Seems network related...
