### ISSUE TITLE
Unable to add cluster due to incomplete and holey project listing

### ISSUE THREAD

**Issue by DazWilkin** [bitnami/cabin#61]
I am a member of hundreds of GCP projects. Many are projects for which I inherit permissions through Groups and the majority of time I'm not interested in the majority of these.

When I first tried Cabin (Android), I was able to add GKE clusters. Recently, I am presented with a list of 12 projects -- 4 include Project IDs, the remaining 8 items are blank. If the list is of GCP Project Names rather than Project IDs, this may provide an explanation.

I am able to select any of the projects in the list (incl. blanks) but the vast majority do not have GKE clusters. I am unable to scroll to uncover more projects. None of the projects I'd like to use (which are mine and which have clusters) is accessible. I am thus unable to make use of Cabin.

RECOMMEND:
-- Either provide a search to filter the list of returned Projects
-- Or support paging of the Project list
-- And provide a list of recently used Projects
-- And reference Project IDs in the list as the customary key rather than Project Name (nullable?)

I work with GCP customers and it is increasingly common for these customers to also have hundreds of GCP Projects.

I'm willing to help beta test any improvements.

**Comment by kemcake** [comment]
The scroll issue should be fixed with #1, and I will investigate the issue with project IDs.
But definitely the UI is not ready to support hundreds of projects, this would definitely need a entire new page with ability to fetch them all, search and/or a quick scroll with alphabet sections.

**Comment by DazWilkin** [comment]
cloudresourcemanager.projects.list supports  (I believe) server-side filing by labels.

While I am a member of hundreds of projects, I'm only interested in a handful. Being able to type a specific Project ID or provide a label would be very helpful.

Unfortunately, otherwise, Cabin is of no use because I'm entirely unable to access my clusters with it.
