### ISSUE TITLE
Where are my credentials ?

### ISSUE THREAD

**Issue by sharkoz** [bitnami/cabin#63]
Sorry if it's a newbie question, but I have a local minikube instance set up thant I can access with my browser at the adress http://192.168.1.XX:30000, but I don't know how to add it in Cabin.

I tried to set this address with no auth but it didn't work.
I tried to add the value of the token I found in the secrets page (default-token-xxx) in the 'token' field, but it didn't work either...
I tried the minikube/minikube user/pass but no luck... Any idea ?
Thx

**Comment by kemcake** [comment]
Minikube use a certificate to authenticate. Minikube store the certificates and keys here /Users/You/.minikube/ or `~/.minikube/`. Go there and run this command:
```
openssl pkcs12 -export -out minikube.p12 -inkey apiserver.key -in apiserver.crt -certfile ca.crt 
```
This create a minikube.p12 certificate that you can use in Cabin. (You'll need to have the certificate downloadable from a url, I use dropbox for that)

This workflow should definitely be improved and documented at some point, but this is how I manage to use minikube in Cabin.

Also the url should be the url defined in your `~/.kube/config` file

**Comment by sharkoz** [comment]
OK thanks !
As of now I have the latest version from the Play Store, v0.3, and I see no option for using a certificate (only user/pass or token). 
I subscribed to the Beta program to see if a newer version is available.

**Comment by kemcake** [comment]
Oh wow yes I just realized I never published the 0.3.1 android beta to production due to an playstore issue, I should do that soon.

**Comment by sebgoa** [comment]
@kemcake did you publish 0.3.1 ? can we close this

**Comment by kemcake** [comment]
Yes, this is a user issue we can close this.
