### ISSUE TITLE
Clusters used to work, but now show as "Down" Always

### ISSUE THREAD

**Issue by EIrwin** [bitnami/cabin#70]
I installed this, added my `Staging` and `Production` cluster which worked and reported healthy.

When I go back to look at them (any time in future). Both clusters are reporting being `Down`. I have obviously confirmed that they are up and running.

When I click into a cluster, none of the resources (Pods, Services, etc) are able to be viewed.

![screenshot_20170914-130447](https://user-images.githubusercontent.com/6673161/30450099-1626dc98-994e-11e7-8259-04d97f5ae58f.png)

**Comment by kemcake** [comment]
Do you use https ? A big connectivity issue, involving https and certificate vertification, has been fixed on Android with #72

**Comment by kemcake** [comment]
@EIrwin Is this fixed with latest update to 0.4.0 ?

**Comment by EIrwin** [comment]
@kemcake This seems to have solved the issue on my end! 👍

**Comment by kemcake** [comment]
Great to hear 🙌

**Comment by smustafa75** [comment]
I m still having this issue on 0.4.0 version.
