### ISSUE TITLE
Cabin can’t get any info from my cluster

### ISSUE THREAD

**Issue by ftab** [bitnami/cabin#71]
I saw the green light that indicates it’s running, but none of the tabs (pods, etc.) show any data, just the loading indicator.

![3fdbe455-7912-4eae-95e2-321f611aac90](https://user-images.githubusercontent.com/1690894/30515372-423a737e-9af4-11e7-957f-5b9aa464fc90.png)

I’m not quite sure how to get logs from the Kubernetes cluster to see if there’s an authentication error. I didn’t enter a username and password because there isn’t one, as far as I know (just a self signed CA and a token, which I got from the config that kubeadm generates)

Here’s a snippet describing how I set up my cluster: https://gitlab.com/snippets/1674542

So in Cabin, I put https://192.168.1.22:6443/ and pasted the CA and token from the admin.conf that was generated after running kubeadm

Is that the right way to set it up?

**Comment by kemcake** [comment]
Ok this is an issue with token authentication, similar to #69. The cluster is seen as running but probably returns `unauthorized` because token is not used correctly, need to investigate how cabin should use the token...
See #69

**Comment by jordanwilson230** [comment]
Same issue here after upgrading to the latest version.
