### ISSUE TITLE
Certificate Auth

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#8]
_From @ccatlett2000 on December 12, 2016 14:51_

Hello, I have a Kubernetes cluster that I can't access because cabin doesn't support cert auth. Could this be added?

_Copied from original issue: skippbox/cabin-issues#19_

**Comment by sebgoa** [comment]
You want client certificates for auth, instead of token or basic auth ?

If yes, how do you envision do provide the certs in the app ?

We have a solution in dev, but it requires putting the cert somewhere it can be downloaded and would be insecure if done over the public internet.

**Comment by sebgoa** [comment]
_From @ccatlett2000 on December 15, 2016 20:19_

I don't intend for the app to have to deal with getting the cert securely to the device, I can do that myself. Obviously just dropping it on a webserver somewhere isn't secure, but that is outside of cabin's control.

**Comment by kemcake** [comment]
@sebgoa , I think we can close this issue and open a new one about security of uploading certificates to cabin ?
